FROM archlinux

RUN pacman -Syu --noconfirm && pacman -S --noconfirm sudo git curl
RUN useradd -m -s /bin/bash user && echo "user:user" | chpasswd && usermod -aG wheel user
RUN echo "%wheel ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers

USER user
WORKDIR /home/user

COPY --chown=user:user . /home/user/dotfiles

WORKDIR /home/user/dotfiles
RUN sudo chmod +x bash/*.sh

CMD ["/home/user/dotfiles/bash/install.sh"]
